//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 10:32:30 PM EEST 
//


package entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cooler" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="energy" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="group" type="{http://www.example.org/simpleXMLSchema}Group"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractType", propOrder = {
    "cooler",
    "energy",
    "group"
})
@XmlSeeAlso({
    External.class,
    Internal.class
})
public class AbstractType {

    protected boolean cooler;
    protected double energy;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Group group;

    /**
     * Gets the value of the cooler property.
     * 
     */
    public boolean isCooler() {
        return cooler;
    }

    /**
     * Sets the value of the cooler property.
     * 
     */
    public void setCooler(boolean value) {
        this.cooler = value;
    }

    /**
     * Gets the value of the energy property.
     * 
     */
    public double getEnergy() {
        return energy;
    }

    /**
     * Sets the value of the energy property.
     * 
     */
    public void setEnergy(double value) {
        this.energy = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Group }
     *     
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Group }
     *     
     */
    public void setGroup(Group value) {
        this.group = value;
    }

}
