//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 10:32:30 PM EEST 
//


package entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for extPort.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="extPort">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="LPT"/>
 *     &lt;enumeration value="USB"/>
 *     &lt;enumeration value="COM"/>
 *     &lt;enumeration value="VGA"/>
 *     &lt;enumeration value="SVGA"/>
 *     &lt;enumeration value="JET"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "extPort")
@XmlEnum
public enum ExtPort {

    LPT,
    USB,
    COM,
    VGA,
    SVGA,
    JET;

    public String value() {
        return name();
    }

    public static ExtPort fromValue(String v) {
        return valueOf(v);
    }

}
