//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.20 at 10:32:30 PM EEST 
//


package entities;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExternalType_QNAME = new QName("http://www.example.org/simpleXMLSchema", "externalType");
    private final static QName _Cooler_QNAME = new QName("http://www.example.org/simpleXMLSchema", "cooler");
    private final static QName _AbstractType_QNAME = new QName("http://www.example.org/simpleXMLSchema", "abstractType");
    private final static QName _InternalType_QNAME = new QName("http://www.example.org/simpleXMLSchema", "internalType");
    private final static QName _Energy_QNAME = new QName("http://www.example.org/simpleXMLSchema", "energy");
    private final static QName _Group_QNAME = new QName("http://www.example.org/simpleXMLSchema", "group");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link External }
     * 
     */
    public External createExternal() {
        return new External();
    }

    /**
     * Create an instance of {@link AbstractType }
     * 
     */
    public AbstractType createAbstractType() {
        return new AbstractType();
    }

    /**
     * Create an instance of {@link Computer }
     * 
     */
    public Computer createComputer() {
        return new Computer();
    }

    /**
     * Create an instance of {@link Device }
     * 
     */
    public Device createDevice() {
        return new Device();
    }

    /**
     * Create an instance of {@link Internal }
     * 
     */
    public Internal createInternal() {
        return new Internal();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link External }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/simpleXMLSchema", name = "externalType", substitutionHeadNamespace = "http://www.example.org/simpleXMLSchema", substitutionHeadName = "abstractType")
    public JAXBElement<External> createExternalType(External value) {
        return new JAXBElement<External>(_ExternalType_QNAME, External.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/simpleXMLSchema", name = "cooler")
    public JAXBElement<Boolean> createCooler(Boolean value) {
        return new JAXBElement<Boolean>(_Cooler_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/simpleXMLSchema", name = "abstractType")
    public JAXBElement<AbstractType> createAbstractType(AbstractType value) {
        return new JAXBElement<AbstractType>(_AbstractType_QNAME, AbstractType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Internal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/simpleXMLSchema", name = "internalType", substitutionHeadNamespace = "http://www.example.org/simpleXMLSchema", substitutionHeadName = "abstractType")
    public JAXBElement<Internal> createInternalType(Internal value) {
        return new JAXBElement<Internal>(_InternalType_QNAME, Internal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/simpleXMLSchema", name = "energy")
    public JAXBElement<BigInteger> createEnergy(BigInteger value) {
        return new JAXBElement<BigInteger>(_Energy_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Group }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/simpleXMLSchema", name = "group")
    public JAXBElement<Group> createGroup(Group value) {
        return new JAXBElement<Group>(_Group_QNAME, Group.class, null, value);
    }

}
